2023-11-05 20:49:13,664 INFO - __main__ - Finished setting up the logger.
2023-11-05 20:49:13,666 CRITICAL - utils.logger - Unhandled exception.
Traceback (most recent call last):
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/main.py", line 70, in <module>
    main()
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/main.py", line 41, in main
    dataset = SyntheticDataset(args.n, args.d, args.graph_type, args.degree,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/data_loader/synthetic_dataset.py", line 44, in __init__
    self._setup()
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/data_loader/synthetic_dataset.py", line 49, in _setup
    self.B_bin = SyntheticDataset.simulate_random_dag(self.d, self.degree,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/data_loader/synthetic_dataset.py", line 120, in simulate_random_dag
    B_bin = SyntheticDataset.simulate_er_dag(d, degree, rs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/data_loader/synthetic_dataset.py", line 76, in simulate_er_dag
    B_und_bin = _graph_to_adjmat(G_und)    # Undirected
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/data_loader/synthetic_dataset.py", line 72, in _graph_to_adjmat
    return nx.to_numpy_matrix(G)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'networkx' has no attribute 'to_numpy_matrix'
