2023-11-05 20:48:40,403 INFO - __main__ - Finished setting up the logger.
2023-11-05 20:48:40,405 CRITICAL - utils.logger - Unhandled exception.
Traceback (most recent call last):
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/main.py", line 70, in <module>
    main()
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/main.py", line 38, in main
    set_seed(args.seed)
  File "/Users/valen/Documents/GitHub/golem/golem_PT/src/utils/utils.py", line 34, in set_seed
    torch.random.set_rng_state(seed)
  File "/Users/valen/anaconda3/lib/python3.11/site-packages/torch/random.py", line 18, in set_rng_state
    default_generator.set_state(new_state)
TypeError: expected a torch.ByteTensor, but got int
